on:
  pull-request:
    branches:
      - main
env:
  PRIVATE : ${{ secrets.GOOGLE }}
name: "Pull Request Check"
jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.5'
      - run: |
          touch android/app/google-services.json
          echo $GOOGLE >> android/app/google-services.json
          cat android/app/google-services.json
      - run: flutter pub get
      - run: flutter build apk